services:
  - type: web
    name: personal-brand-os
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    preDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: personal-brand-os-vb3t.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://personal-brand-os-vb3t.onrender.com
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: TOKEN_ENCRYPTION_KEY
        sync: false
