# Generated by Django 5.2.16 on 2026-08-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(default="Tech & AI Trends", max_length=100),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("summary", models.TextField()),
                (
                    "ai_hook",
                    models.TextField(help_text="Suggested post hook generated by AI"),
                ),
                ("category", models.CharField(default="AI_TECH", max_length=50)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
