# Generated by Django 5.2.16 on 2026-08-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("target_audience", models.TextField(blank=True, default="")),
                ("preferred_platforms", models.JSONField(blank=True, default=list)),
                ("content_formats", models.JSONField(blank=True, default=list)),
                ("allocation_percentage", models.IntegerField(default=25)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_pillars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("idea", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "LinkedIn"),
                            ("X", "X (Twitter)"),
                            ("X_THREAD", "X Thread"),
                            ("YOUTUBE", "YouTube Video"),
                            ("YOUTUBE_SHORT", "YouTube Short"),
                            ("INSTAGRAM_REEL", "Instagram Reel"),
                            ("CAROUSEL", "Carousel"),
                            ("BLOG", "Blog Article"),
                            ("NEWSLETTER", "Newsletter"),
                            ("REDDIT", "Reddit"),
                            ("FACEBOOK", "Facebook"),
                            ("THREADS", "Threads"),
                            ("STORY", "Story"),
                        ],
                        default="LINKEDIN",
                        max_length=50,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "LinkedIn"),
                            ("X", "X (Twitter)"),
                            ("X_THREAD", "X Thread"),
                            ("YOUTUBE", "YouTube Video"),
                            ("YOUTUBE_SHORT", "YouTube Short"),
                            ("INSTAGRAM_REEL", "Instagram Reel"),
                            ("CAROUSEL", "Carousel"),
                            ("BLOG", "Blog Article"),
                            ("NEWSLETTER", "Newsletter"),
                            ("REDDIT", "Reddit"),
                            ("FACEBOOK", "Facebook"),
                            ("THREADS", "Threads"),
                            ("STORY", "Story"),
                        ],
                        default="LINKEDIN",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("RESEARCHING", "Researching"),
                            ("DRAFT", "Draft"),
                            ("AI_GENERATED", "AI Generated"),
                            ("EDITING", "Editing"),
                            ("APPROVED", "Approved"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="IDEA",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("hook", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
                ("cta", models.TextField(blank=True, default="")),
                ("hashtags", models.CharField(blank=True, default="", max_length=500)),
                ("keywords", models.CharField(blank=True, default="", max_length=500)),
                ("references", models.TextField(blank=True, default="")),
                ("source_urls", models.TextField(blank=True, default="")),
                ("script", models.TextField(blank=True, default="")),
                ("caption", models.TextField(blank=True, default="")),
                ("visual_instructions", models.TextField(blank=True, default="")),
                ("thumbnail_idea", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_items",
                        to="content.contentpillar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("content_snapshot", models.JSONField()),
                (
                    "change_reason",
                    models.CharField(blank=True, default="Manual Edit", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.contentitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="content.contentitem",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.contentversion",
                    ),
                ),
            ],
        ),
    ]
