from django.db import models


class NewsArticle(models.Model):
    title = models.CharField(max_length=255)
    source = models.CharField(max_length=100, default="Tech & AI Trends")
    url = models.URLField(max_length=500, blank=True, null=True)
    summary = models.TextField()
    ai_hook = models.TextField(help_text="Suggested post hook generated by AI")
    category = models.CharField(max_length=50, default="AI_TECH")
    published_at = models.DateTimeField(auto_now_add=True)
    ingested_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-published_at"]

    def __str__(self):
        return f"{self.title} ({self.source})"
