# Generated by Django 5.2.16 on 2026-08-23 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("STRATEGIST", "Content Strategist"),
                            ("IDEATOR", "Idea Generator"),
                            ("WRITER", "Writer"),
                            ("SCRIPTWRITER", "Script Writer"),
                            ("REPURPOSER", "Content Repurposer"),
                            ("REVIEWER", "Brand Reviewer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("system_prompt", models.TextField()),
                ("user_prompt_template", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("input_text", models.TextField()),
                ("output_text", models.TextField()),
                ("execution_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
