# Generated by Django 5.2.16 on 2026-08-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentexecutionlog",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentexecutionlog",
            name="model_tier",
            field=models.CharField(
                choices=[
                    ("FLAGSHIP", "Flagship Tier (250k/day quota)"),
                    ("MINI_NANO", "Mini/Nano Tier (2.5M/day quota)"),
                ],
                default="MINI_NANO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agentexecutionlog",
            name="model_used",
            field=models.CharField(default="gpt-4o-mini", max_length=50),
        ),
        migrations.AddField(
            model_name="agentexecutionlog",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentexecutionlog",
            name="total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
