# Generated by Django 5.2.16 on 2026-08-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0002_agentexecutionlog_completion_tokens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicResearchCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RESEARCHING", "Researching & Fact Checking"),
                            ("GENERATING_MEDIUM", "Drafting Medium Article"),
                            ("GENERATING_REEL", "Writing Instagram Reel Script"),
                            ("GENERATING_LINKEDIN", "Creating LinkedIn Post"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("research_notes", models.TextField(blank=True, default="")),
                ("fact_check_summary", models.TextField(blank=True, default="")),
                ("medium_blog", models.TextField(blank=True, default="")),
                ("insta_reel_script", models.TextField(blank=True, default="")),
                ("insta_reel_caption", models.TextField(blank=True, default="")),
                ("linkedin_post", models.TextField(blank=True, default="")),
                (
                    "medium_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to published Medium blog post",
                    ),
                ),
                (
                    "insta_reel_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to published Instagram Reel",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
