# Generated by Django 5.2.16 on 2026-08-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0003_topicresearchcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicresearchcampaign",
            name="research_depth",
            field=models.CharField(
                choices=[
                    ("QUICK", "Quick"),
                    ("STANDARD", "Standard"),
                    ("DEEP", "Deep"),
                ],
                default="DEEP",
                max_length=20,
            ),
        ),
    ]
