# Generated by Django 5.2.16 on 2026-08-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "professional_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("short_bio", models.CharField(blank=True, default="", max_length=500)),
                ("long_bio", models.TextField(blank=True, default="")),
                ("positioning_statement", models.TextField(blank=True, default="")),
                ("niche", models.CharField(blank=True, default="", max_length=255)),
                ("target_audience", models.TextField(blank=True, default="")),
                ("expertise", models.TextField(blank=True, default="")),
                ("skills", models.TextField(blank=True, default="")),
                (
                    "languages",
                    models.CharField(blank=True, default="English", max_length=255),
                ),
                ("content_goals", models.TextField(blank=True, default="")),
                ("career_story", models.TextField(blank=True, default="")),
                ("achievements", models.TextField(blank=True, default="")),
                ("education", models.TextField(blank=True, default="")),
                ("experience", models.TextField(blank=True, default="")),
                ("workshops", models.TextField(blank=True, default="")),
                ("publications", models.TextField(blank=True, default="")),
                ("portfolio_url", models.URLField(blank=True, default="")),
                ("social_profiles", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandVoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="Authoritative yet accessible",
                        max_length=255,
                    ),
                ),
                (
                    "sentence_length",
                    models.CharField(
                        blank=True, default="Short to medium", max_length=255
                    ),
                ),
                ("vocabulary_preferences", models.TextField(blank=True, default="")),
                ("words_to_avoid", models.TextField(blank=True, default="")),
                ("phrases_to_avoid", models.TextField(blank=True, default="")),
                ("preferred_hooks", models.TextField(blank=True, default="")),
                (
                    "cta_style",
                    models.CharField(
                        blank=True, default="Direct and value-driven", max_length=255
                    ),
                ),
                (
                    "technical_depth",
                    models.CharField(
                        blank=True, default="Intermediate to Advanced", max_length=255
                    ),
                ),
                (
                    "audience_level",
                    models.CharField(
                        blank=True, default="Professionals & Engineers", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_voice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
