# Generated by Django 5.2.16 on 2026-08-23 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("LINKEDIN", "LinkedIn"),
                            ("X_TWITTER", "X / Twitter"),
                            ("YOUTUBE", "YouTube"),
                            ("GITHUB", "GitHub"),
                            ("THREADS", "Threads"),
                            ("MEDIUM", "Medium"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "handle",
                    models.CharField(help_text="e.g. @cellstocode", max_length=100),
                ),
                ("profile_url", models.URLField(blank=True, default="")),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage engagement rate e.g. 4.5"
                    ),
                ),
                ("total_impressions", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-followers_count"],
                "unique_together": {("user", "platform")},
            },
        ),
    ]
