# Generated by Django 5.2.16 on 2026-08-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="citations_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="stars_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "LinkedIn"),
                    ("X_TWITTER", "X / Twitter"),
                    ("YOUTUBE", "YouTube"),
                    ("GITHUB", "GitHub"),
                    ("THREADS", "Threads"),
                    ("MEDIUM", "Medium"),
                    ("ORCID", "ORCID Research"),
                    ("RESEARCHGATE", "ResearchGate"),
                    ("FACEBOOK", "Facebook"),
                ],
                max_length=50,
            ),
        ),
    ]
