# Generated by Django 5.2.16 on 2026-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_socialaccount_citations_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="last_post_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="target_cadence_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Target frequency in days (e.g. 2 for IG, 3 for LinkedIn, 7 for GitHub)",
            ),
        ),
    ]
