# Generated by Django 5.2.16 on 2026-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_socialaccount_last_post_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="access_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="provider_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
